global:
  scrape_interval: 10s
  external_labels:
    origin_prom: prometheus-server.ironhide.nodes.rogena.me
scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['systemd-prometheus-node-exporter-ironhide:9100']
        labels:
          nodename: ironhide
          domainname: nodes.rogena.me
  - job_name: 'podman'
    static_configs:
      - targets: ['systemd-prometheus-podman-exporter-ironhide:9882']
        labels:
          nodename: ironhide
          domainname: nodes.rogena.me
